"""Presentation layer dependencies."""

from app.presentation.dependencies.handlers import (
    CreateLogHandlerDep,
    CreateUserHandlerDep,
    DeleteUserHandlerDep,
    GetLogByIdHandlerDep,
    GetUserByEmailHandlerDep,
    GetUserByIdHandlerDep,
    GetUserByUsernameHandlerDep,
    ListLogsByUserHandlerDep,
    ListLogsHandlerDep,
    ListUsersHandlerDep,
    UpdateUserHandlerDep,
    get_create_log_handler,
    get_create_user_handler,
    get_delete_user_handler,
    get_list_logs_by_user_handler,
    get_list_logs_handler,
    get_list_users_handler,
    get_log_by_id_handler,
    get_update_user_handler,
    get_user_by_email_handler,
    get_user_by_id_handler,
    get_user_by_username_handler,
)
from app.presentation.dependencies.repositories import (
    get_log_read_model_repository,
    get_log_repository,
    get_user_read_model_repository,
    get_user_repository,
    set_log_read_model_repository,
    set_log_repository,
    set_user_read_model_repository,
    set_user_repository,
)
from app.presentation.dependencies.services import (
    get_event_bus,
    get_password_hasher,
    get_user_domain_service,
    set_event_bus,
    set_password_hasher,
)

__all__ = [
    # Repository providers
    "get_user_repository",
    "get_log_repository",
    "get_user_read_model_repository",
    "get_log_read_model_repository",
    "set_user_repository",
    "set_log_repository",
    "set_user_read_model_repository",
    "set_log_read_model_repository",
    # Service providers
    "get_event_bus",
    "get_password_hasher",
    "get_user_domain_service",
    "set_event_bus",
    "set_password_hasher",
    # Handler providers
    "get_create_user_handler",
    "get_update_user_handler",
    "get_delete_user_handler",
    "get_user_by_id_handler",
    "get_user_by_email_handler",
    "get_user_by_username_handler",
    "get_list_users_handler",
    "get_create_log_handler",
    "get_log_by_id_handler",
    "get_list_logs_handler",
    "get_list_logs_by_user_handler",
    # Handler type aliases
    "CreateUserHandlerDep",
    "UpdateUserHandlerDep",
    "DeleteUserHandlerDep",
    "GetUserByIdHandlerDep",
    "GetUserByEmailHandlerDep",
    "GetUserByUsernameHandlerDep",
    "ListUsersHandlerDep",
    "CreateLogHandlerDep",
    "GetLogByIdHandlerDep",
    "ListLogsHandlerDep",
    "ListLogsByUserHandlerDep",
]
