"""Presentation layer dependencies."""

from app.presentation.dependencies.handlers import (
    # Assignment handler type aliases
    AssignPermissionToRoleHandlerDep,
    AssignPermissionToUserHandlerDep,
    AssignRoleToUserHandlerDep,
    # User handler type aliases
    CreateLogHandlerDep,
    # Permission handler type aliases
    CreatePermissionHandlerDep,
    # Role handler type aliases
    CreateRoleHandlerDep,
    CreateUserHandlerDep,
    DeletePermissionHandlerDep,
    DeleteRoleHandlerDep,
    DeleteUserHandlerDep,
    GetLogByIdHandlerDep,
    GetPermissionByIdHandlerDep,
    GetPermissionByNameHandlerDep,
    GetRoleByIdHandlerDep,
    GetRoleByNameHandlerDep,
    GetRolePermissionsHandlerDep,
    GetUserByEmailHandlerDep,
    GetUserByIdHandlerDep,
    GetUserByUsernameHandlerDep,
    GetUserEffectivePermissionsHandlerDep,
    GetUserRolesHandlerDep,
    ListLogsByUserHandlerDep,
    ListLogsHandlerDep,
    ListPermissionsHandlerDep,
    ListRolesHandlerDep,
    ListUsersHandlerDep,
    RemovePermissionFromRoleHandlerDep,
    RemovePermissionFromUserHandlerDep,
    RemoveRoleFromUserHandlerDep,
    UpdatePermissionHandlerDep,
    UpdateRoleHandlerDep,
    UpdateUserHandlerDep,
    # Handler factory functions
    get_create_log_handler,
    get_create_user_handler,
    get_delete_user_handler,
    get_list_logs_by_user_handler,
    get_list_logs_handler,
    get_list_users_handler,
    get_log_by_id_handler,
    get_update_user_handler,
    get_user_by_email_handler,
    get_user_by_id_handler,
    get_user_by_username_handler,
)
from app.presentation.dependencies.repositories import (
    get_assignment_repository,
    get_log_read_model_repository,
    get_log_repository,
    get_permission_read_model_repository,
    get_permission_read_repository,
    get_permission_write_repository,
    get_role_read_model_repository,
    get_role_read_repository,
    get_role_write_repository,
    get_unit_of_work,
    get_user_read_model_repository,
    get_user_read_repository,
    get_user_write_repository,
    set_log_read_model_repository,
    set_log_repository,
)
from app.presentation.dependencies.services import (
    get_event_bus,
    get_password_hasher,
    set_event_bus,
    set_password_hasher,
)

__all__ = [
    # Unit of Work
    "get_unit_of_work",
    # Repository providers (PostgreSQL - request-scoped, separated read/write)
    "get_user_write_repository",
    "get_user_read_repository",
    "get_user_read_model_repository",
    "get_role_write_repository",
    "get_role_read_repository",
    "get_role_read_model_repository",
    "get_permission_write_repository",
    "get_permission_read_repository",
    "get_permission_read_model_repository",
    "get_assignment_repository",
    # Repository providers (MongoDB - app-scoped)
    "get_log_repository",
    "get_log_read_model_repository",
    "set_log_repository",
    "set_log_read_model_repository",
    # Service providers
    "get_event_bus",
    "get_password_hasher",
    "set_event_bus",
    "set_password_hasher",
    # Handler providers
    "get_create_user_handler",
    "get_update_user_handler",
    "get_delete_user_handler",
    "get_user_by_id_handler",
    "get_user_by_email_handler",
    "get_user_by_username_handler",
    "get_list_users_handler",
    "get_create_log_handler",
    "get_log_by_id_handler",
    "get_list_logs_handler",
    "get_list_logs_by_user_handler",
    # User handler type aliases
    "CreateUserHandlerDep",
    "UpdateUserHandlerDep",
    "DeleteUserHandlerDep",
    "GetUserByIdHandlerDep",
    "GetUserByEmailHandlerDep",
    "GetUserByUsernameHandlerDep",
    "ListUsersHandlerDep",
    "CreateLogHandlerDep",
    "GetLogByIdHandlerDep",
    "ListLogsHandlerDep",
    "ListLogsByUserHandlerDep",
    # Role handler type aliases
    "CreateRoleHandlerDep",
    "UpdateRoleHandlerDep",
    "DeleteRoleHandlerDep",
    "GetRoleByIdHandlerDep",
    "GetRoleByNameHandlerDep",
    "ListRolesHandlerDep",
    # Permission handler type aliases
    "CreatePermissionHandlerDep",
    "UpdatePermissionHandlerDep",
    "DeletePermissionHandlerDep",
    "GetPermissionByIdHandlerDep",
    "GetPermissionByNameHandlerDep",
    "ListPermissionsHandlerDep",
    # Assignment handler type aliases
    "AssignRoleToUserHandlerDep",
    "RemoveRoleFromUserHandlerDep",
    "AssignPermissionToUserHandlerDep",
    "RemovePermissionFromUserHandlerDep",
    "AssignPermissionToRoleHandlerDep",
    "RemovePermissionFromRoleHandlerDep",
    "GetUserRolesHandlerDep",
    "GetUserEffectivePermissionsHandlerDep",
    "GetRolePermissionsHandlerDep",
]
