"""IAM presentation dependency providers."""

from app.iam.presentation.dependencies.handlers import (
    AssignPermissionToRoleHandlerDep,
    AssignPermissionToUserHandlerDep,
    AssignRoleToUserHandlerDep,
    CreatePermissionHandlerDep,
    CreateRoleHandlerDep,
    CreateUserHandlerDep,
    DeletePermissionHandlerDep,
    DeleteRoleHandlerDep,
    DeleteUserHandlerDep,
    GetPermissionByIdHandlerDep,
    GetPermissionByNameHandlerDep,
    GetRoleByIdHandlerDep,
    GetRoleByNameHandlerDep,
    GetRolePermissionsHandlerDep,
    GetUserByEmailHandlerDep,
    GetUserByIdHandlerDep,
    GetUserByUsernameHandlerDep,
    GetUserEffectivePermissionsHandlerDep,
    GetUserRolesHandlerDep,
    ListPermissionsHandlerDep,
    ListRolesHandlerDep,
    ListUsersHandlerDep,
    PasswordHasherDep,
    RemovePermissionFromRoleHandlerDep,
    RemovePermissionFromUserHandlerDep,
    RemoveRoleFromUserHandlerDep,
    UpdatePermissionHandlerDep,
    UpdateRoleHandlerDep,
    UpdateUserHandlerDep,
)
from app.iam.presentation.dependencies.repositories import (
    IamUnitOfWorkDep,
    PermissionReadModelRepositoryDep,
    RoleReadModelRepositoryDep,
    UserReadModelRepositoryDep,
)

__all__ = [
    "IamUnitOfWorkDep",
    "PasswordHasherDep",
    "UserReadModelRepositoryDep",
    "RoleReadModelRepositoryDep",
    "PermissionReadModelRepositoryDep",
    # User
    "CreateUserHandlerDep",
    "UpdateUserHandlerDep",
    "DeleteUserHandlerDep",
    "GetUserByIdHandlerDep",
    "GetUserByEmailHandlerDep",
    "GetUserByUsernameHandlerDep",
    "ListUsersHandlerDep",
    # Role
    "CreateRoleHandlerDep",
    "UpdateRoleHandlerDep",
    "DeleteRoleHandlerDep",
    "GetRoleByIdHandlerDep",
    "GetRoleByNameHandlerDep",
    "ListRolesHandlerDep",
    # Permission
    "CreatePermissionHandlerDep",
    "UpdatePermissionHandlerDep",
    "DeletePermissionHandlerDep",
    "GetPermissionByIdHandlerDep",
    "GetPermissionByNameHandlerDep",
    "ListPermissionsHandlerDep",
    # Assignment
    "AssignRoleToUserHandlerDep",
    "RemoveRoleFromUserHandlerDep",
    "AssignPermissionToUserHandlerDep",
    "RemovePermissionFromUserHandlerDep",
    "AssignPermissionToRoleHandlerDep",
    "RemovePermissionFromRoleHandlerDep",
    "GetUserRolesHandlerDep",
    "GetUserEffectivePermissionsHandlerDep",
    "GetRolePermissionsHandlerDep",
]
